config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :csv_product_imports
  end
end

app/models/csv_product_import.rb
class CsvProductImport < ActiveRecord::Base
  belongs_to :taxon
  validates_length_of :filename, :maximum => 100
end

app/models/product_decorator.rb
Product.class_eval do
  validates :code, :uniqueness => true, :length => { :maximum => 20 }
end

app/controllers/admin/csv_product_imports_controller.rb
# -*- coding: utf-8 -*-
class Admin::CsvProductImportsController < Admin::BaseController
  def index
    @csv_product_imports = CsvProductImport.order('created_at DESC')
  end

  def new
    @csv_product_import = CsvProductImport.new
  end

  def create
    parameters = params[:csv_product_import]
    @csv_product_import = CsvProductImport.new(parameters.merge({ :status => 'in_progress' }))
    @file = params[:file]
    @csv_product_import.filename = @file.original_filename

    if @csv_product_import.save
      File.open(File.join(Rails.root, 'tmp', @file.original_filename), 'w') do |file|
        file.write(@file.read)
      end

      command = %{cd #{Rails.root} && RAILS_ENV=#{Rails.env} rake spree_csv_import:parse_csv task_id=#{@csv_product_import.id}#{" update_only=1" if @csv_product_import.update_only} &}
      system command

      redirect_to admin_csv_product_imports_path
    else
      render :new
    end
  end

  def show
    @csv_product_import = CsvProductImport.find(params[:id])
  end
end

app/views/admin/csv_product_imports/index.html.erb
<h1><%= t('csv_import.csv_imports') %></h1>

<% if @csv_product_imports.any? %>
<table class="index">
  <tr>
    <th><%= t('csv_import.status') %></th>
    <th><%= t('csv_import.import_date') %></th>
    <th><%= t('csv_import.parsed_date') %></th>
    <th><%= t('csv_import.filename') %></th>
    <th><%= t('csv_import.update_only') %></th>
    <th><%= t('csv_import.inserted_products_count') %></th>
    <th><%= t('csv_import.updated_products_count') %></th>
    <th><%= t('csv_import.loaded_images_count') %></th>
    <th></th>
  </tr>
  <% @csv_product_imports.each do |ci| %>
  <tr>
    <td><%= t("csv_import.status_#{ci.status}") %></td>
    <td><%= ci.created_at.to_s %></td>
    <td><%= ci.parsed_date %></td>
    <td><%= ci.filename %></td>
    <td><%= ci.update_only ? t(:yes) : t(:no) %></td>
    <td><%= ci.inserted_products_count %></td>
    <td><%= ci.updated_products_count %></td>
    <td><%= ci.loaded_images_count %></td>
    <td><%= link_to t('show'), admin_csv_product_import_path(ci) %></td>
  </tr>
  <% end %>
</table>
<% else %>
  <div><%= t('csv_import.there_is_no_csv_tasks') %></div>
<% end %>

<%= link_to "<span>#{t('csv_import.import_csv')}</span>".html_safe, new_admin_csv_product_import_path, :class => 'button' %>

app/views/admin/csv_product_imports/new.html.erb
<h1><%= t('csv_import.csv_imports') %></h1>

<% if @csv_product_import.try(:errors).present? %>
  <%= render 'shared/error_messages', :target => @csv_product_import %>
<% end %>

<%= form_for [:admin, @csv_product_import], :html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :taxon_id, t("csv_import.taxon") %><br/>
    <%= f.error_message_on :taxon_id %>
    <%= f.select "taxon_id", Taxon.all.collect {|p| [ p.name, p.id ] } %>
  </p>

  <p>
    <%= label_tag :file, t("csv_import.file") %>
    <%= file_field_tag :file %>
  </p>

  <p>
    <%= label_tag :update_only, t("csv_import.update_only") %>
    <%= f.check_box :update_only %>
  </p>

  <p>
    <p class="form-buttons">
      <%= button t("actions.create") %>
      <%= t("or") %> <%= link_to t("actions.cancel"), admin_csv_product_imports_path %>
    </p>
  </p>
<% end %>

app/views/admin/csv_product_imports/show.html.erb
<h1><%= t('csv_import.csv_imports') %></h1>

<p>
  <%= t('csv_import.status')%>: <%= t("csv_import.status_#{@csv_product_import.status}") %>
</p>

<p>
  <%= t('csv_import.filename') %>: <%= @csv_product_import.filename %>
</p>

<p>
  <%= t('csv_import.import_date') %>: <%= @csv_product_import.created_at.to_s %>
</p>

<p>
  <%= t('csv_import.parsed_date') %>: <%= @csv_product_import.parsed_date.to_s %>
</p>

<p>
  <%= t('csv_import.update_only') %>: <%= @csv_product_import.update_only ? t(:yes) : t(:no) %>
</p>

<p>
  <%= t('csv_import.inserted_products_count') %>: <%= @csv_product_import.inserted_products_count %>
</p>

<p>
  <%= t('csv_import.updated_products_count') %>: <%= @csv_product_import.updated_products_count %>
</p>

<p>
  <%= link_to t('back'), admin_csv_product_imports_path %>
</p>

app/views/admin/products/new.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render "shared/error_messages", :target => @product %>

<%= form_for(:product,  :url => collection_url, :html => { :multipart => true }) do |f| %>
<fieldset>

  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= f.text_field :name, :class => 'fullwidth title'  %>
    <%= f.error_message_on :name %>
  <% end %>

  <%= f.field_container :code do %>
    <%= f.label :code, t("csv_import.code") %> <span class="required">*</span><br />
    <%= f.text_field :code, :class => 'fullwidth title'  %>
    <%= f.error_message_on :code %>
  <% end %>

  <div class="yui-gb">
    <div class="yui-u first">

      <% unless @product.has_variants? %>
      <%= f.field_container :sku do %>
        <%= f.label :sku, t("sku") %><br />
        <%= f.text_field :sku, :size => 16 %>
        <%= f.error_message_on :sku %>
      <% end %>
      <% end %>

      <p>
        <%= f.label :prototype_id, t("prototype") %><br />
        <%= f.collection_select :prototype_id, Prototype.all, :id, :name, :include_blank => true %>
      </p>

    </div>
    <div class="yui-u">

      <%= f.field_container :price do %>
        <%= f.label :price, t("master_price")%> <span class="required">*</span><br />
        <%= f.text_field :price  %>
        <%= f.error_message_on :price%>
      <% end %>

      <p>
        <%= f.label :available_on, t("available_on") %><br />
        <%= f.error_message_on :available_on %>
        <%= f.spree_date_picker :available_on, :style=>"width:150px" %>
      </p>


    </div>
  </div>

  <%= render :partial => 'admin/shared/new_resource_links' %>

</fieldset>
<% end %>
<%= javascript_tag "datePickerController.create();" %>